# Generated by Django 5.2.1 on 2025-05-23 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Encargados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_tienda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('detalles', models.TextField(max_length=500)),
                ('fotografia', models.ImageField(upload_to='tiendas')),
                ('activo', models.BooleanField(default=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encargados.encargado')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'db_table': 'Tienda',
            },
        ),
    ]
