# Generated by Django 5.2.1 on 2025-05-23 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Celulares', '0001_initial'),
        ('Clientes', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle_venta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celulares.celular')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'Detalle_Venta',
            },
        ),
    ]
