# Generated by Django 5.2.1 on 2025-05-23 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tiendas', '0001_initial'),
        ('Vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id_celular', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('almacenamiento', models.IntegerField(choices=[(8, '8GB'), (16, '16GB'), (32, '32GB'), (64, '64GB'), (128, '128GB'), (256, '256GB'), (512, '512GB'), (1024, '1TB')])),
                ('ram', models.IntegerField(choices=[(4, '4GB'), (6, '6GB'), (8, '8GB'), (12, '12GB'), (16, '16GB')])),
                ('estado', models.IntegerField()),
                ('detalles', models.TextField(max_length=500)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('imei2', models.CharField(max_length=15, null=True, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendas.tienda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendedores.vendedor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Celulares.marca')),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
                'db_table': 'Celular',
            },
        ),
    ]
