# Generated by Django 5.2.1 on 2025-06-03 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Celulares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='imagenes',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='celulares'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celular',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Como nuevo'), (1, 'Detalles esteticos'), (2, 'Detalles Fuertes')]),
        ),
    ]
